fbook/fbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

from .views import search_friends

#Uwzględnienie innych plików url, połączenie
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls',namespace='profiles')),
    path('posts/', include('posts.urls',namespace='posts')),

    path('search_friends/', search_friends, name='search-friends'),
]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fbook/posts/urls.py
from django.urls import path
from .views import post_create_comment
from .views import like_unlike_post
from .views import PostDelete
from .views import PostUpdate

#zarejestrowanie adresu url postu
app_name='posts'

urlpatterns = [
    path('', post_create_comment, name='post-view'),
    path('liked/', like_unlike_post, name='like-post'),
    path('<pk>/update/', PostUpdate.as_view(), name='post-edit'),
    path('<pk>/delete/', PostDelete.as_view(), name='post-delete'),
]

fbook/profiles/urls.py
from django.urls import path
from .views import profileuser_view
from .views import invites_received
from .views import list_of_profiles_friends
from .views import ProfileList
from .views import invatation_send
from .views import remove_friend
from .views import invite_remove, invite_accept
from .views import ProfileDetail

#zajerestrowanie adresu url profilu pojedynczego usera
app_name='profiles'
urlpatterns = [
    path('', ProfileList.as_view(), name='profiles-all'),
    path('profileuser/', profileuser_view, name='profile-user-view'),
    path('profilinvites/', invites_received, name='profile-invites'),
    path('profilefriends/', list_of_profiles_friends, name='profiles-friends'),
    path('sendinvatation/', invatation_send, name='invite-send'),
    path('removefriends/', remove_friend, name='remove-friends'),
    path('inviteremove/', invite_remove, name='invite-remove'),
    path('inviteaccept/', invite_accept, name='invite-accept'),
    path('<slug>/', ProfileDetail.as_view(), name='profile-detail'),
]

fbook/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.shortcuts import reverse

# Create your models here.

class ProfileManage(models.Manager):

    #uzyskanie wszystkich profilów z wyjątkiem naszego
    def get_profiles_all(self, myprof):
        #wszystkie profile oprócz mojego
        profiles = Profile.objects.all().exclude(user=myprof)
        return profiles

    #wszystkie profile z którymi jesteśmy znajomymi
    def get_profiles_all_friends(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        #wszystkie relacje w których jesteśmy nadawcą lub odbiorcą zaproszenia
        set_of_queries = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        #lista wszystkich znajomych
        invites_accepted = set([])
        print(set_of_queries)
        #przejście przez zestaw zapytań
        for relation in set_of_queries:
            #czy zaproszenie zostało zaakceptowane
            if relation.status == 'accepted':
                invites_accepted.add(relation.receiver)
                invites_accepted.add(relation.sender)
        print(invites_accepted)
        #wszyscy znajomi oprócz swojego profilu
        profiles_to_invite = [profile for profile in profiles if profile in invites_accepted]
        print(profiles_to_invite)
        return profiles_to_invite

#profil
#blanki zmienić potem
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    bio = models.TextField(default="brak biografii", max_length=300)
    avatar = models.ImageField(default='avatar.png', upload_to='avatars/')
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    #etykieta
    slug = models.SlugField(unique=True, blank=True)
    objects = ProfileManage()

    #wczyscy znajomi, widoczne jest to w pliku profileuser.html poprzez pętle for
    def get_friends(self):
        return self.friends.all()

    #ilość znajomych
    def get_count_friends(self):
        return self.friends.all().count()

    #tytuł profilu, który zawiera nazwę usera oraz czas w jakim został utworzony profil, reprezentacja tekstowa
    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"

    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *arg, **kwargs):
        super().__init__(*arg, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    #nadawanie oryginalnej etykiety
    #*args i **kwargs pozwalają na przekazanie nieokreślonej liczby argumentów do funkcji, nie trzeba wiedzieć ile argumentów zostaje przekazanych do funkcji
    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        #jeśli identyfikator jest pusty bądź jest zmieniony, nie jest równe początkowemu
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug == "":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_code()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)

    #licznik danych postów przez użytkownika
    def get_count_posts(self):
        return self.posts.all().count()

    def get_authors_all_posts(self):
        return self.posts.all()

    #licznik danych polubień przez użytkownika
    def get_count_likes(self):
        total_liked = 0
        liked = self.like_set.all()
        for x in liked:
            if x.value == 'Like':
                total_liked +=1
        return total_liked

    #licznik danych nie polubień przez użytkownika
    def get_count_unlikes(self):
        total_unliked = 0
        Unlikes = self.like_set.all()
        for x in Unlikes:
            if x.value == 'Unlike':
                total_unliked +=1
        return total_unliked

    #liczba otrzymanych polubień/nie polubień, aktywność
    #pobieramy konkretny post, uzyskujemy dostęp do pola polubień
    #następnie pobieramy wszystkie polubienia poszczególnych postów oraz liczymy je
    def get_count_received_likes(self):
        total_liked = 0
        posts = self.posts.all()
        for x in posts:
            total_liked+=x.liked.all().count()
        return total_liked

    #zobacz profil
    def get_show_profil(self):
        return reverse("profiles:profile-detail", kwargs={"slug": self.slug})


#wybór między wysłanym zaproszeniem do znajomych a zaakceptowanym
STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)

#menadżer relacji
class RelationshipManage(models.Manager):
    def invatations_received(self, receiver):
        set_of_queries = Relationship.objects.filter(receiver=receiver, status='send')
        return set_of_queries

#relacje
class Relationship(models.Model):
    #nadawca
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    #odbiorca
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    #status
    status = models.CharField(max_length=8,choices=STATUS_CHOICES)
    objects = RelationshipManage()
    #tytuł relacji, która zawiera odbiorcę, nadawcę i jej status, albo sent-wysłana czyli nieprzyjęta jeszcze przez drugiego użytkownika albo accepted-zaakceptowana, reprezentacja tekstowa
    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

fbook/profiles/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
from .models import Profile
from .models import Relationship
from .form_update import ProfileModelForm

#widok pojedynczego usera, poprzez przekazanie informacji usera
#widok aktualizacji profilu
@login_required
def profileuser_view(request):
    profile = Profile.objects.get(user=request.user)

    # aktualizowanie konkretnego profilu
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile )
    confirm_form = False

    #sprawdzenie poprawności, czy formularz jest poprawny
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm_form = True

    #zmienne kontekstowe
    context = {
        'profile' : profile,
        'form' : form,
        'confirm_form': confirm_form,
    }
    #zwrócenie widoku
    return render(request, 'profiles/profileuser.html', context)

#widok otrzymanego zaproszenia
@login_required
def invites_received(request):
    profile = Profile.objects.get(user=request.user)
    set_of_queries = Relationship.objects.invatations_received(profile)
    empty = False
    res=list(map(lambda x: x.sender, set_of_queries))
    #jeśli nie ma żadnych zaproszeń
    if len(res)==0:
        empty=True
    #zmienne kontekstowe
    context = {
        'empty' : empty,
        'set_of_queries' : res,
    }
    #zwrócenie widoku
    return render(request, 'profiles/profilinvites.html', context)

#lista profili
@login_required
def list_of_profiles(request):
    user = request.user
    set_of_queries = Profile.objects.get_profiles_all(user)

    # zmienne kontekstowe
    context = {
        'set_of_queries': set_of_queries,
    }
    # zwrócenie widoku
    return render(request, 'profiles/list_profiles.html', context)

#lista możliwych zaproszeń
@login_required
def list_of_profiles_friends(request):
    user = request.user
    set_of_queries = Profile.objects.get_profiles_all_friends(user)

    # zmienne kontekstowe
    context = {
        'set_of_queries': set_of_queries,
    }
    # zwrócenie widoku
    return render(request, 'profiles/all_friends.html', context)

class ProfileList(LRM ,ListView):
    #określenie modelu
    model = Profile
    #wskazanie szablonu do widoku
    template_name = 'profiles/list_profiles.html'
    #określenie listy obiektów do wyświetlenia
    def get_queryset(self):
        set_of_queries = Profile.objects.get_profiles_all(self.request.user)
        return set_of_queries

    #metoda służąca do wypełnienia słownika która używana jest jako kontekst szablonu
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        # przechowywanie relacji w których zaprosiliśmy innych użytkowników do znajomych
        receiver_relation = Relationship.objects.filter(sender=profile)
        #relacja zapoczątkowana od innych użytkowników
        sender_relation = Relationship.objects.filter(receiver=profile)
        sender_relation_list = []
        receiver_relation_list = []
        #dołączenie relacji do list
        for y in receiver_relation:
            receiver_relation_list.append(y.receiver.user)
        for y in sender_relation:
            sender_relation_list.append(y.sender.user)
        #zmienne kontekstowe
        context["receiver_relation_list"] = receiver_relation_list
        context["sender_relation_list"] = sender_relation_list
        #jeśli długość naszego zapytania jest równa zero
        context['is_empty'] = False
        #to tworzymy inny klucz w słowniku kontekstowym
        if len(self.get_queryset()) == 0:
            context['is empty'] = True
        return context

#wysyłanie zaproszeń do znajomych
@login_required
def invatation_send(request):
    #jeśli mamy do czynienia z żądaniem post, uzyskujemy dostęp do tego adresu URL który zamierzamy zarejestrować
    if request.method=="POST":
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)
        relat = Relationship.objects.create(sender=sender, receiver=receiver, status='send')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:profile-user-view')

#usuwanie ze znajomych
@login_required
def remove_friend(request):
    if request.method=="POST":
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        relat = Relationship.objects.get((Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender)))
        relat.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:profile-user-view')

#widok zaakceptowanego zaproszenia
@login_required
def invite_accept(request):
    if request.method == "POST":
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        relat = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if relat.status == 'send':
            relat.status = 'accepted'
            relat.save()
    return redirect('profiles:profile-invites')

#widok usuniętego zaproszenia
@login_required
def invite_remove(request):
    if request.method == "POST":
        pk = request.POST.get('profile_pk')
        receiver = Profile.objects.get(user=request.user)
        sender = Profile.objects.get(pk=pk)
        relat = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        relat.delete()
    return redirect('profiles:profile-invites')

#widok profilu innego użytkownika
class ProfileDetail(LRM ,DetailView):
    model = Profile
    template_name = 'profiles/profile_particular.html'
    def get_object(self, slug=None):
        slug = self.kwargs.get('slug')
        profile = Profile.objects.get(slug=slug)
        return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        # przechowywanie relacji w których zaprosiliśmy innych użytkowników do znajomych
        receiver_relation = Relationship.objects.filter(sender=profile)
        #relacja zapoczątkowana od innych użytkowników
        sender_relation = Relationship.objects.filter(receiver=profile)
        sender_relation_list = []
        receiver_relation_list = []
        #dołączenie relacji do list
        for y in receiver_relation:
            receiver_relation_list.append(y.receiver.user)
        for y in sender_relation:
            sender_relation_list.append(y.sender.user)
        #zmienne kontekstowe
        context["receiver_relation_list"] = receiver_relation_list
        context["sender_relation_list"] = sender_relation_list
        #wszystkie posty użytkownika
        context["posts"] = self.get_object().get_authors_all_posts()
        context["post_user_len"] = True \
            if len(self.get_object().get_authors_all_posts()) >0 else False
        return context

fbook/profiles/templates/profiles/list_profiles.html
{% extends 'base.html' %}
{% block title %}Wszyscy użytkownicy{% endblock title %}
{% block content %}
    <!--Jeśli nie ma żadnego profilu to wyświetl-->
    {% if is_empty %}
        <h3>Nie ma profilów</h3>
    {% endif %}
    <!--wyświetlanie użytkowników-->
    {% for x in object_list %}
        <div class="ui fluid card">
            <div class="content">
                <div class="ui grid">
                    <div class="row">
                        <!--układ wielokolumnowy-->
                        <div class="three wide column">
                            <!--Okrągłe zdjęcie profilowe-->
                            <img class="ui small circular image" src="{{x.avatar.url}}">
                        </div>
                        <!--przycisk zależnie od relacji-->
                        <div class="nine wide column">
                            <!--informacje o użytkowniku-->
                            <h2>{{ x.user }}</h2>
                            <p>{{ x.bio }}</p>
                            <a href={{ x.get_show_profil }}>
                                <button class="ui primary button marginb">Zobacz profil</button>
                            </a>
                        </div>
                        <div class="four wide column">
                            <!--Jeśli użytkownik nie przyjaźni się z tym użytkownikem, oraz nie wysłał zaproszenia to można dodać go do znajomych-->
                            {% if x.user not in receiver_relation_list and x.user not in sender_relation_list %}
                                <form action="{% url 'profiles:invite-send' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{ x.pk }}">
                                    <button type="submit" class="ui primary button marginb">
                                        <i class="plus square icon"></i>Dodaj do znajomych
                                    </button>
                                </form>
                            {% endif %}
                            <!--Jeśli wysłano już zaproszenie do znajomych-->
                            {% if x.user in receiver_relation_list and request.user not in x.friends.all %}
                                <button class="ui disable button">
                                    <i class="user icon"></i>Wysłano zaproszenie
                                </button>
                            {% endif %}
                            <!--Jeśli użytkownik się przyjaźni z danych użytkowniem to może go usunąć-->
                            {% if request.user in x.friends.all %}
                                <form action="{% url 'profiles:remove-friends' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{ x.pk }}">
                                    <button type="submit" class="ui primary button marginb">
                                        <i class="minus square icon"></i>Usuń ze znajomych
                                    </button>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

fbook/profiles/templates/profiles/profile_particular.html
{% extends 'base.html' %}
{%  block title %}Zobacz profil użytkownika
{% endblock title %}
{% block scripts %}
    <script>
        $( document ).ready(function() {
            let shw = true
            $(".clicksw").click(function () {
                //jeśli komentarze są pokazane/rozsunięte
                if (shw===true) {
                    //to po kliknięciu komentarz zostają schowane szybko
                    $(this).next(".comment-box").hide("fast");
                    shw=false
                }
                //Jeśli komentarze są schowane
                else {
                    //to po kliknięciu pokaż komentarze/rozsuń szybko
                    $(this).next(".comment-box").show("fast");
                    shw=true
                }
            });
        });
    </script>
{% endblock scripts %}
{%  block content %}
    <div class="ui grid">
        <br>
        <div class="row">
            <!--układ wielokolumnowy-->
            <!--dane i statystyki-->
            <div class="five wide column">
                <img class="ui medium rounded image" src={{ object.avatar.url }}>
                <table class="ui table">
                    <tbody>
                        <tr>
                            <td>Użytkownik</td>
                            <td>{{ object.user }}</td>
                        </tr>
                        {% if object.first_name != "" %}
                            <tr>
                                <td>Imie</td>
                                <td>{{ object.first_name }}</td>
                            </tr>
                        {% endif %}
                        {% if object.last_name != "" %}
                            <tr>
                                <td>Nazwisko</td>
                                <td>{{ object.last_name }}</td>
                            </tr>
                        {% endif %}
                        {% if object.country != "" %}
                            <tr>
                                <td>Miejsce zamieszkania</td>
                                <td>{{ object.country }}</td>
                            </tr>
                        {% endif %}
                        {% if object.email != "" %}
                            <tr>
                                <td>Email</td>
                                <td>{{ object.email }}</td>
                            </tr>
                        {% endif %}
                        <tr>
                            <td>Biografia</td>
                            <td>{{ object.bio }}</td>
                        </tr>
                        <tr>
                            <td>Data dołączenia</td>
                            <td>{{ object.created }}</td>
                        </tr>
                    </tbody>
                </table>
                <!--Jeśli użytkownik nie przyjaźni się z tym użytkownikem, oraz nie wysłał zaproszenia to można dodać go do znajomych-->
                    {% if object.user not in receiver_relation_list and object.user not in sender_relation_list %}
                        <form action="{% url 'profiles:invite-send' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{ object.pk }}">
                            <button type="submit" class="ui primary button marginb">
                                <i class="plus square icon"></i>Dodaj do znajomych
                            </button>
                        </form>
                    {% endif %}
                    <!--Jeśli wysłano już zaproszenie do znajomych-->
                    {% if object.user in receiver_relation_list and request.user not in object.friends.all %}
                        <button class="ui disable button">
                            <i class="user icon"></i>Wysłano zaproszenie
                        </button>
                    {% endif %}
                    <!--Jeśli użytkownik się przyjaźni z danych użytkowniem to może go usunąć-->
                    {% if request.user in object.friends.all %}
                        <form action="{% url 'profiles:remove-friends' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{ object.pk }}">
                            <button type="submit" class="ui primary button marginb">
                                <i class="minus square icon"></i>Usuń ze znajomych
                            </button>
                        </form>
                    {% endif %}


                <div class="ui vertical fluid menu">
                    <div class="item">
                        Liczba znajomych
                        <div class="ui label">{{ object.get_count_friends }}</div>
                    </div>
                    <div class="item">
                        Posty
                        <div class="ui label">{{ object.get_count_posts }}</div>
                    </div>
                    <div class="item">
                        Polubienia
                        <div class="ui label">{{ object.get_count_likes }}</div>
                    </div>
                    <div class="item">
                        Otrzymane polubienia
                        <div class="ui label">{{ object.get_count_received_likes }}</div>
                    </div>
                </div>
            </div>
            <!--posty-->
            <div class="eleven wide column">
            {% if request.user in object.friends.all %}
                {% if post_user_len %}
                    {% for post in posts %}
                        <div class="ui fluid card">
				            <div class="content">
                                <!--reprezentacja stringu, nazwa użytkownika i czas kiedy został dodany post-->
                                <img class="ui avatar image" src={{post.author.avatar.url}}>
                                {{ post.author.user }} &nbsp {{ post.created|timesince}} temu
                            </div>
                            <div class="ui fluid image">
                                {% if post.image %}
                                    <img src={{post.image.url}}>
                                {% endif %}
                            </div>
                            <div class="content">
                                <p> {{ post.content }} </p>
                                <div class="right floated">
                                    <form action="{% url 'posts:like-post' %}" method="POST" class="like-form" id="{{ post.id }}">
                                    <!--ochrona prze fałszowaniem żądań pomiędzy witrynami-->
                                        {% csrf_token %}
                                    <input type="hidden" name="post_id" value={{post.id}}>
                                        <!--liczba polubień-->
                                        <div class="ui grid">
                                            <div class="column">
                                                <div class="like-count{{ post.id }}">
                                                    {{post.likes_number}}
                                                </div>
                                            </div>
                                            <div class="column">
                                                Polubień
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="extra content">
                                <div class="marginb"></div>
                                <i class="comment icon"></i>
                                <!--liczba komentarzy-->
                                <span> {{ post.comments_count }} komentarzy</span>
                                <br><br>
                                <!--pokazywanie i ukrywanie komentarzy, wykonywanie jest za pomocą skryptu java script-->
                                <button class="clicksw ui button marginb">pokaż/schowaj komentarze</button>
                                <div class="comment-box">
                                    <!--Jeśli komentarz istnieje-->
                                    {% if post.comment_set.all %}
                                        <!--to przeglądamy je w pętli, wyświetlane są na ekranie od najmłodszego na górze do najstarszego na dole-->
                                        {% for i in post.comment_set.all %}
                                            <div class="ui segment marginb">
                                                <img class="ui avatar image" src={{i.user.avatar.url}}>
                                                <!--user i czas kiedy został komentarz utworzony-->
                                                <span>{{ i.user.user }}&nbsp{{ i.created|timesince}}&nbsptemu</span>
                                                    <div class='margint'>
                                                        {{ i.body }}
                                                    </div>
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    {% else %}
                        <h3>{{ object.user }}&nbspnie ma żadnych opublikowanych postów</h3>

                {% endif %}
            {% else %}
                <h2>Nie jesteś znajomym tego użytkownika, podgląd postów tego użytkonika jest zabronione</h2>
            {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

fbook/profiles/templates/profiles/profilinvites.html
{% extends 'base.html' %}
{% block title %}Zaproszenia{% endblock title %}
{% block content %}
    {% if empty %}
        <h3>Nie masz żadnych zaproszeń</h3>
    {% endif %}
    {% for x in set_of_queries %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <!--układ wielokolumnowwy-->
                    <div class="four wide column">
                        <!--małe okrągłe zdjęcie awatara-->
                        <img class="ui small circular image" src={{ x.avatar.url}}>
                    </div>
                    <div class="eight wide column">
                        <h2>{{ x.user }}</h2>
                        <p>{{ x.bio }}</p>
                        <a href="">
                            <button class="ui primary button marginb">zobacz profil</button>
                        </a>
                    </div>
                    <div class="four wide column">
                        <form action="{% url 'profiles:invite-accept' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{ x.pk }}>
                            <button type="submit" class="ui primary button marginb">
                                <i class="check icon"></i>Zaakceptuj zaproszenie
                            </button>
                        </form>
                        <form action="{% url 'profiles:invite-remove' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{ x.pk }}>
                            <button type="submit" class="ui primary button marginb">
                                <i class="close icon"></i>Usuń zaproszenie
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}