fbook/fbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

from .views import search_friends

#Uwzględnienie innych plików url, połączenie
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls',namespace='profiles')),
    path('posts/', include('posts.urls',namespace='posts')),

    path('search_friends/', search_friends, name='search-friends'),
]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fbook/posts/urls.py
from django.urls import path
from .views import post_create_comment
from .views import like_unlike_post
from .views import PostDelete
from .views import PostUpdate

#zarejestrowanie adresu url postu
app_name='posts'

urlpatterns = [
    path('', post_create_comment, name='post-view'),
    path('liked/', like_unlike_post, name='like-post'),
    path('<pk>/update/', PostUpdate.as_view(), name='post-edit'),
    path('<pk>/delete/', PostDelete.as_view(), name='post-delete'),
]

fbook/posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile

#klasa posty
class Post(models.Model):
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')
    image = models.ImageField(upload_to='posts', validators=[FileExtensionValidator(['jpeg', 'jpg', 'png', 'bmp'])], blank=True)
    liked = models.ManyToManyField(Profile, related_name='likes', blank=True)

    #max 250 znaków tytuł posta
    def __str__(self):
        return str(self.content[:250])

    #licznik polubień pod postem
    def likes_number(self):
        return self.liked.all().count()

    #liczba komentarzy pod postem
    def comments_count(self):
        return self.comment_set.all().count()

    #komentarz posegregowane od najnowszego na górze do najstarszego na dole
    class comments:
        ordering = ('-author',)

#klasa komentarze
class Comment(models.Model):
    #klucz obcy z klasy profile
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    #klucz obcy z klasy post
    post = models. ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=250)

    def __str__(self):
        return str(self.pk)

#wybór między polubieniem czy nie polubieniem
LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike')
)

#klasa polubienia
class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=6)

    #reprezentacja tekstowa
    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

fbook/posts/views.py
from django.shortcuts import render, redirect
from django.views.generic import UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
from django.http import JsonResponse
from .models import Post, Like
from profiles.models import Profile
from .form_post import PostModelForm
from .form_post import CommentModelForm
from django.db.models import Count

#widok tworzenia komentarzy
#login_requred to zabezpieczenie strony, wymaga zalogowania się
@login_required
def post_create_comment(request):

    # przechowywanie wszystkich obiektów w zmiennej według liczby like
    set_of_queries = Post.objects.annotate(q_count=Count('liked')).order_by('q_count')

    #pobieranie określonej ilości postów
    #set_of_queries = Post.objects.all().[:5]

    profile = Profile.objects.get(user=request.user)

    form_post = PostModelForm()
    form_comment = CommentModelForm()

    # Informacje na temat konkretnego użytkownika
    profile = Profile.objects.get(user=request.user)

    #wartość początkowa
    new_post = False
    new_comment = False

    #formularz posta
    #Jeśli przesyłanie wykonuje się w żądaniu postu to formularz zostanie przesłany a następnie wykonuje się poniższy kod
    if 'submit_form_post' in request.POST:
        print(request.POST)
        form_post = PostModelForm(request.POST, request.FILES)
        # jesli formularz postu jest prawidłowy
        if form_post.is_valid():
            object = form_post.save(commit=False)
            # przypisz do zewnętrznego pola ten profil
            object.author = profile
            # zapisanie obiektu
            object.save()
            form_post = PostModelForm()
            new_post = True

    #formularz komentarza
    if 'submit_form_comment' in request.POST:
        form_comment = CommentModelForm(request.POST)
        # jeśli formularz komentarza jest prawidłowy
        if form_comment.is_valid():
            object2 = form_comment.save(commit=False)
            # to przypisz usera który jest aktualnie zalogowany
            object2.user = profile
            # pobranie wiadomości
            object2.post = Post.objects.get(id=request.POST.get('post_id'))
            # zapisanie obiektu
            object2.save()
            form_comment = CommentModelForm()
            new_comment = True

    #zmienne kontekstowe
    context={
        'new_post' : new_post,
        'set_of_queries' : set_of_queries,
        'profile' : profile,
        'form_post' : form_post,
        'form_comment' : form_comment,
        'new_comment' : new_comment
    }

    # zwrócenie widoku, powyższych kluczy można potem użyć w .html
    return render(request, 'posts/postuser.html', context)
@login_required
def like_unlike_post(request):
    # jeśli użytkownik jest zalogowany to ustaw na tego użytkownika
    user = request.user
    # sprawdzenie czy mamy do czynienia z żądaniem wiadomości
    if request.method == 'POST':
        # pobierz identyfikator wiadomości
        post_id = request.POST.get('post_id')
        # uzyskanie obiektu posta
        post_x = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)
        # jeśli użytkownik już kliknął polubienie
        if profile in post_x.liked.all():
            # to jeśli kliknie drugi raz to odznaczy polubienie
            post_x.liked.remove(profile)
        else:
            # w przeciwnym razie, polubi ten post
            post_x.liked.add(profile)

        # reakcje pod postem, umożliwiające automatyczne wpisanie do bazy wartości
        like, created = Like.objects.get_or_create(user=profile, post_id=post_id)
        # pierwsze kliknięcie będzie polubieniem, zaś ponowne kliknięcie będzie unlikiem
        if not created:
            if like.value=='Like':
                like.value='Unlike'
            else:
                like.value='Like'
            post_x.save()
            like.save()
        else:
            like.value='Like'
            post_x.save()
            like.save()

        data = {
            'value' : like.value,
            'likes' : post_x.liked.all().count(),
        }
        return JsonResponse(data, safe=False)

    # zwrócenie widoku postu
    return redirect('posts:post-view')

#klasa do edycji posta
class PostUpdate(LRM ,UpdateView):
    form_class = PostModelForm
    model = Post
    #wskazanie szablonu
    template_name = 'posts/postupdate.html'
    success_url = reverse_lazy('posts:post-view')
    # czy użytkownik jest autorem postu
    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        # jeśli nie jest to autor tego postu to nie edytuje tego postu
        if form.instance.author != profile:
            form.add_error(None, "Nie możesz edytować tego postu ponieważ nie jesteś jego autorem")
            return super().form_invalid(form)
        # w przeciwnym wypadku przejdzie do edycji postu
        else:
            return super().form_valid(form)

# klasa usuwania formularza
class PostDelete(LRM ,DeleteView):
    #określenie modelu
    model = Post
    # wskazanie szablonu
    template_name = 'posts/postdel.html'
    # jeśli nastąpi pomyślnie usunięcie posta to wrócimy do głównej strony postów
    success_url = reverse_lazy('posts:post-view')
    # czy obecnie zalogowany użytkownik to autor postu
    def get_object(self, *args, **kwargs):
        #uzyskanie klucza głównego
        pk = self.kwargs.get('pk')
        x = Post.objects.get(pk=pk)
        # jeśli nie jest to autor tego postu to nie może go usunąć
        if not x.author.user == self.request.user:
            messages.warning(self.request, 'Nie można usunąć postu ponieważ nie jesteś autorem tego postu')
        return x

fbook/posts/templates/posts/postdel.html
{% extends 'base.html' %}
{% block title %}Usunięcie posta{% endblock title %}
{% block content %}
    <!--jeśli wiadomości istnieją-->
    {% if messages %}
        <!-- to wyświetlaj-->
        {% for message in messages %}
            <!-- tylko i wyłącznie negatywane wiadomości z błędami-->
            {% if 'warning' in message.tags %}
                <div class="ui negative message">
                    <div class="header">
                        {{ message }}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if not messages %}
        <div class="ui segment">
            <form action="" method="POST">
                <h2>Czy chcesz usunąć ten post ?</h2>
                {% csrf_token %}
                <button type="submit" class="ui button primary margint">
                   Usuń post
                </button>
            </form>
        </div>
    {% endif %}
{% endblock content %}

fbook/posts/templates/posts/postupdate.html
{% extends 'base.html' %}
{% block title %}aktualizacja posta{% endblock title %}
{% block content %}
    <div class="ui segment">
        <h2>Edycja postu</h2>
        <form action="" class="ui form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="ui button primary margint">Zaktualizuj post</button>
        </form>
    </div>
{% endblock content %}

fbook/posts/templates/posts/postuser.html
{% extends 'base.html' %}
{% block title %}posty{% endblock title %}
<!--jeśli przyciśniemy przycisk rozwinięcia komentarzy to wykona się poniższy kod-->
{% block scripts %}
    <script>
        $( document ).ready(function() {
            let shw = true
            $(".clicksw").click(function () {
                //jeśli komentarze są pokazane/rozsunięte
                if (shw===true) {
                    //to po kliknięciu komentarz zostają schowane szybko
                    $(this).next(".comment-box").hide("fast");
                    shw=false
                }
                //Jeśli komentarze są schowane
                else {
                    //to po kliknięciu pokaż komentarze/rozsuń szybko
                    $(this).next(".comment-box").show("fast");
                    shw=true
                }
            });

            $('.like-form').submit(function(e){
                //uniemożliwienie odświeżania się strony
                e.preventDefault()
                const post_id = $(this).attr('id')
                const likeText = $(`.like-btn${ post_id }`).text()
                const trim = $.trim(likeText)
                const url = $(this).attr('action')
                let res;
                const likes = $(`.like-count${ post_id }`).text()
                const trimCount = parseInt(likes)
                $.ajax({
                    //typ
                    type:'POST',
                    //ustawienie adresu url
                    url: url,
                    data:{
                        'csrfmiddlewaretoken' : $('input[name=csrfmiddlewaretoken]').val(),
                        'post_id' : post_id
                    },
                    success: function(response){
                        if(trim==='Unlike'){
                            $(`.like-btn${ post_id }`).text('Like')
                            res = trimCount -1
                        }
                        else{
                            $(`.like-btn${ post_id }`).text('Unlike')
                            res = trimCount +1
                        }
                        $(`.like-count${ post_id }`).text(res)
                    },
                    error: function(response){
                        console.log('error', response)
                    }
                })
            });
        });
    </script>
{% endblock scripts %}
{% block content %}
	<div class="ui grid">
        <!--układ wielokolumnowy-->
		<div class="fourteen wide column">
            <div class="ui segment">
                {% if new_post %}
                    <!--Wiadomość w zielonym okienku-->
                    <div class="ui green message">Dodano nowy post</div>
                {% endif %}
                {% if new_comment %}
                    <div class="ui green message">Dodano nowy komentarz</div>
                {% endif %}
                <form action="" class='ui form' method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form_post}}
                    <button class="ui primary button w-full margint" type='submit' name="submit_form_post">Opublikuj post</button>
                </form>
            </div>
            <!--wyświetlane posty są od najmłodszego (na górze) do najstarszego (na dole)-->
			{% for x in set_of_queries reversed %}
                {% if request.user in x.author.friends.all or request.user == x.author.user %}
                    <!--karta-->
    			    <div class="ui fluid card">
				        <div class="content">
					        <div class="right floated meta">
					            <div class="ui grid">
						            <div class="row">
                                    <!--Jeśli jest to użytkownik który upublicznił ten post to ujrzy przyciski usuń lub edytuj-->
                                        {% if request.user == x.author.user %}
                                            <!--należy przekazać oprócz adresu jeszcze klucz główny-->
                                            <a href="{% url 'posts:post-edit' x.pk %}"><button class="ui button transparent_bg ">Edytuj</button></a>
								            <a href="{% url 'posts:post-delete' x.pk %}"><button class="ui button transparent_bg ">Usuń</button></a>
							            {% endif %}
						            </div>
					            </div>
                            </div>
                            <!--reprezentacja stringu, nazwa użytkownika i czas kiedy został dodany post-->
                            <img class="ui avatar image" src={{x.author.avatar.url}}>
                            {{ x.author.user }} &nbsp {{ x.created|timesince}} temu
                        </div>
                        <div class="ui fluid image">
                            {% if x.image %}
                                <img src={{x.image.url}}>
                            {% endif %}
                        </div>
                        <div class="content">
                            <p> {{ x.content }} </p>
                            <div class="right floated">
                                <form action="{% url 'posts:like-post' %}" method="POST" class="like-form" id="{{ x.id }}">
                                <!--ochrona prze fałszowaniem żądań pomiędzy witrynami-->
                                    {% csrf_token %}
                                <input type="hidden" name="post_id" value={{x.id}}>
                                    <button type="submit" class="ui primary button like-btn{{ x.id }}">
                                        <!--jeśli polubione-->
                                        {% if profile not in x.liked.all %}Like
                                        <!--w przeciwnym wypadku-->
                                        {% else %}Unlike
                                        {% endif %}
                                    </button>
                                    <!--liczba polubień-->
                                    <div class="ui grid">
                                        <div class="column">
                                            <div class="like-count{{ x.id }}">
                                                {{x.likes_number}}
                                            </div>
                                        </div>
                                        <div class="column">
                                            Polubień
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="extra content">
                            <div class="marginb"></div>
                            <i class="comment icon"></i>
                            <!--liczba komentarzy-->
                            <span> {{ x.comments_count }} komentarzy</span>
                            <br><br>
                            <!--pokazywanie i ukrywanie komentarzy, wykonywanie jest za pomocą skryptu java script-->
                            <button class="clicksw ui button marginb">pokaż/schowaj komentarze</button>
                            <div class="comment-box">
                                <!--Jeśli komentarz istnieje-->
                                {% if x.comment_set.all %}
                                    <!--to przeglądamy je w pętli, wyświetlane są na ekranie od najmłodszego na górze do najstarszego na dole-->
                                    {% for i in x.comment_set.all %}
                                        <div class="ui segment marginb">
                                            <img class="ui avatar image" src={{i.user.avatar.url}}>
                                            <!--user i czas kiedy został komentarz utworzony-->
                                            <span>{{ i.user.user }}&nbsp{{ i.created|timesince}}&nbsptemu</span>
                                                <div class='margint'>
                                                    {{ i.body }}
                                                </div>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <form class='ui fluid form' action="" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value={{x.id}}>
                                    {{ form_comment }}
                                <button type="submit" class="ui primary button margint w-full" name="submit_form_comment">Opublikuj komentarz</button>
                            </form>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock content %}