fbook/fbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

from .views import search_friends

#Uwzględnienie innych plików url, połączenie
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls',namespace='profiles')),
    path('posts/', include('posts.urls',namespace='posts')),

    path('search_friends/', search_friends, name='search-friends'),
]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fbook/posts/urls.py
from django.urls import path
from .views import post_create_comment
from .views import like_unlike_post
from .views import PostDelete
from .views import PostUpdate

#zarejestrowanie adresu url postu
app_name='posts'

urlpatterns = [
    path('', post_create_comment, name='post-view'),
    path('liked/', like_unlike_post, name='like-post'),
    path('<pk>/update/', PostUpdate.as_view(), name='post-edit'),
    path('<pk>/delete/', PostDelete.as_view(), name='post-delete'),
]

fbook/profiles/urls.py
from django.urls import path
from .views import profileuser_view
from .views import invites_received
from .views import list_of_profiles_friends
from .views import ProfileList
from .views import invatation_send
from .views import remove_friend
from .views import invite_remove, invite_accept
from .views import ProfileDetail

#zajerestrowanie adresu url profilu pojedynczego usera
app_name='profiles'
urlpatterns = [
    path('', ProfileList.as_view(), name='profiles-all'),
    path('profileuser/', profileuser_view, name='profile-user-view'),
    path('profilinvites/', invites_received, name='profile-invites'),
    path('profilefriends/', list_of_profiles_friends, name='profiles-friends'),
    path('sendinvatation/', invatation_send, name='invite-send'),
    path('removefriends/', remove_friend, name='remove-friends'),
    path('inviteremove/', invite_remove, name='invite-remove'),
    path('inviteaccept/', invite_accept, name='invite-accept'),
    path('<slug>/', ProfileDetail.as_view(), name='profile-detail'),
]

fbook/templates/main/home.html
{% extends 'base.html' %}
{% block title %}
home
{% endblock title %}
{% block content %}
<br>
    <h1>zalogowany jako: {{user}}</h1>
{% endblock content %}
{% block scripts %}
    <script>
    $(document).ready(function(){
        console.log('dziala')
    })
    </script>
{% endblock scripts %}

fbook/templates/main/navbar.html
{% url 'posts:post-view' as posts_view_path %}
{% url 'home-view' as home_view_path %}
{% url 'profiles:profile-user-view' as profile_user_view_path %}
{% url 'profiles:profile-invites' as profile_invites_view_path %}
{% url 'profiles:profiles-friends' as profile_friends_view_path %}
{% url 'profiles:profiles-all' as profile_all_view_path %}


<!--pasek nawigacyjny-->
<div class="ui inverted menu nav marginb">
    <div class="ui container">
        <a href="{{ home_view_path }}" class="{% if request.path == home_view_path %}active{% endif %} item">
            <h3>fbook</h3>
        </a>
        {% if request.user.is_authenticated %}
            <!--jeśli ścieżka żądania jest równa postom ścieżki, dodana zostaje aktywna klasa-->
        <a href="{{ posts_view_path }}" class="{% if request.path == posts_view_path %}active{% endif %} item">Strona główna</a>
    {% endif %}
        <div class="right menu">
            {% if request.user.is_authenticated %}
                 <div class="item">
                    <form action="{% url 'search-friends' %}" method=POST>
                        <div class="ui action left icon input">
                            {% csrf_token %}
                            <input class="prompt" type="text" name="que" placeholder="wyszukaj znajomego">
                            <i class="search icon"></i>
                            <button type='submit' class="ui button">Znajdź</button>
                        </div>
                    </form>
                </div>
                <div class="item">
                    <div class="ui floating dropdown icon button teal"> Znajomi
                        <i class="dropdown icon"></i>
                        <div class="menu">
                            <a href="{{ profile_all_view_path }}" class="{% if request.path == profile_all_view_path %}active{% endif %} item">Nieznajomi</a>
                            <a href="{{ profile_invites_view_path }}" class="{% if request.path == profile_invites_view_path %}active{% endif %} item">Otrzymane zaproszenia &nbsp;
                                <div class="ui green horizontal label">{{ count_invites_r }}</div></a>
                            <a href="{{ profile_friends_view_path }}" class="{% if request.path == profile_friends_view_path %}active{% endif %} item">Znajomi</a>
                        </div>
                    </div>
                </div>
                <a href="{{ profile_user_view_path }}" class="{% if request.path == profile_user_view_path %}active{% endif %} item">
                    <img src={{ picture.url }} class="ui avatar image">&nbsp;{{ request.user }}</a>
                <a href="{% url 'account_logout' %}" class="ui item">Wyloguj</a>
                {% else %}
                <a href="{% url 'account_login' %}" class="ui item">Login</a>
                {% endif %}
        </div>
    </div>
</div>